apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: operator-api
  name: operator-api
  namespace: ocean-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: operator-api
    spec:
      containers:
      - env:
        - name: REACT_APP_BRIZO_ADDRESS
          value: 0x008c25ed3594e094db4592f4115d5fa74c4f41ea
        image: oceanprotocol/operator-service:test
        imagePullPolicy: Always
        name: operator-api
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        environment: production
      restartPolicy: Always
      serviceAccount: operator-service
      serviceAccountName: operator-service
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

