apiVersion: v1
kind: Service
metadata:
  name: operator-api-nodeport
spec:
  type: NodePort
  selector:
    app: operator-api
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8050
      targetPort: 8050
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31000
